# Generated by Django 6.0.4 on 2026-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='bonus_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
