# Generated by Django 6.0.4 on 2026-04-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_employeedirectoryhibob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedirectoryhibob',
            name='candidate_jobvite_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
