# Generated by Django 6.0.4 on 2026-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_employeedirectoryhibob_candidate_jobvite_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobviteApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_eid', models.CharField(max_length=120, unique=True)),
                ('candidate_eid', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=150, null=True)),
                ('hibob_id', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_state', models.CharField(blank=True, max_length=150, null=True)),
                ('workflow_state_eid', models.CharField(blank=True, max_length=120, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('job_eid', models.CharField(blank=True, max_length=120, null=True)),
                ('requisition_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobvite_applications',
                'indexes': [models.Index(fields=['hibob_id'], name='jobvite_app_hibob_i_33782b_idx'), models.Index(fields=['email'], name='jobvite_app_email_30690d_idx'), models.Index(fields=['requisition_id'], name='jobvite_app_requisi_d152d4_idx'), models.Index(fields=['last_updated_date'], name='jobvite_app_last_up_0b5d37_idx')],
            },
        ),
    ]
