# Generated by Django 6.0.4 on 2026-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_jobviteapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectoryhibob',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedirectoryhibob',
            name='termination_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
