# Generated by Django 6.0.4 on 2026-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_alter_employeedirectoryhibob_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectoryhibob',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedirectoryhibob',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
