# Generated by Django 6.0.4 on 2026-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_alter_employeedirectoryhibob_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobviteRequisitionReferralDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(db_index=True, max_length=100)),
                ('recruiter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interviewer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobvite_requisition_referral_details',
                'indexes': [models.Index(fields=['req_id'], name='jobvite_req_req_id_98f8b5_idx'), models.Index(fields=['recruiter_name'], name='jobvite_req_recruit_ba1821_idx'), models.Index(fields=['hiring_manager_name'], name='jobvite_req_hiring__85fa73_idx'), models.Index(fields=['interviewer_full_name'], name='jobvite_req_intervi_cfec0d_idx')],
            },
        ),
    ]
