# Generated by Django 6.0.4 on 2026-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_jobviterequisitionreferraldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedirectoryhibob',
            name='entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
