# Generated by Django 6.0.4 on 2026-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_employeedirectoryhibob_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_the_referral', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_department', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_title', models.CharField(blank=True, max_length=255, null=True)),
                ('presenter_shuffler', models.CharField(blank=True, max_length=255, null=True)),
                ('table_language', models.CharField(blank=True, max_length=255, null=True)),
                ('full_time_part_time', models.CharField(blank=True, max_length=255, null=True)),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('bonus_amount_eur_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonus_amount_eur_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_type', models.CharField(blank=True, max_length=100, null=True)),
                ('special_campaign_1st_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_campaign_2nd_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_campaign_3rd_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('specificity', models.IntegerField(blank=True, null=True)),
                ('rule_rank', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=20, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'referral_bonus_rules',
                'indexes': [models.Index(fields=['location_of_the_referral'], name='referral_bo_locatio_f0d067_idx'), models.Index(fields=['workflow_title'], name='referral_bo_workflo_3a47e3_idx'), models.Index(fields=['sub_department'], name='referral_bo_sub_dep_0ba62d_idx'), models.Index(fields=['date_effective'], name='referral_bo_date_ef_37e6bb_idx'), models.Index(fields=['date_end'], name='referral_bo_date_en_be7a09_idx'), models.Index(fields=['rule_rank'], name='referral_bo_rule_ra_d1f9a6_idx')],
            },
        ),
    ]
